### ISSUE TITLE
Misaligned icons on the manager dashboard

### ISSUE THREAD

**Issue by vaishalirawat2003** [Peaky-Blinders-CS253-Project/Muli-Integrated#13]
The buttons to access links are wrongly aligned, for example upon clicking the icon next to student info, the manage bdmr page opens.

![Screenshot (137)](https://github.com/Peaky-Blinders-CS253-Project/Muli-Integrated/assets/123720801/2854275f-657b-4dfd-b2d5-b027ce485612)

**Comment by ARNAB5671** [comment]
fixed
