### ISSUE TITLE
Email field doesn't ensure validity of email address

### ISSUE THREAD

**Issue by vaishalirawat2003** [Peaky-Blinders-CS253-Project/Muli-Integrated#14]
Validity of email address format is not checked when saving a new student. Only the presence of @ is ensure so an email like abc@xyz is accepted without the domain part.

![Screenshot (138)](https://github.com/Peaky-Blinders-CS253-Project/Muli-Integrated/assets/123720801/8f32a06f-a2c6-40fa-9ff0-0572c40114de)

**Comment by ARNAB5671** [comment]
manager dependant
