### ISSUE TITLE
Price updation message in student login interface

### ISSUE THREAD

**Issue by vaishalirawat2003** [Peaky-Blinders-CS253-Project/Muli-Integrated#9]
While updating the price for extras, the message for successful updation is shown in the login interface for students.

![Screenshot (136)](https://github.com/Peaky-Blinders-CS253-Project/Muli-Integrated/assets/123720801/0ae077ce-44c9-487e-8fa0-7b7fb8be4da0)

**Comment by ARNAB5671** [comment]
fixed
